## 🔑 What is a Primary Key?

A Primary Key is a column (or group of columns) that makes a row unique. It acts like a Student ID or a Passport Number.

### The 4 Golden Rules of Primary Keys:

1. **Uniqueness**: No two rows can have the same PK value.
2. **Non-null**: PK columns can never be empty (NULL).
3. **Immutable**: Once assigned, the value should not change.
4. **One per Table**: A table can only have one primary key definition.

---

## 🛠️ Creating Primary Keys

There are three ways to define a Primary Key during table creation:

### Method 1: Column-level (Simplest)

```sql
CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name VARCHAR(100)
);
```

````

### Method 2: Table-level

Useful for complex definitions or clarity.

```sql
CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    PRIMARY KEY (student_id)
);

```

### Method 3: Named Constraint (Pro Approach)

Naming your constraint makes it easier to modify or drop later.

```sql
CREATE TABLE students (
    student_id INTEGER,
    name VARCHAR(100),
    CONSTRAINT pk_students PRIMARY KEY (student_id)
);

```

---

## 🧬 Single vs. Composite Primary Keys

### Single Primary Key

Uses one column (like `student_id`) to identify the row.

### Composite Primary Key

Uses **multiple columns** together. This is common in "link" tables where one column isn't enough to be unique.

```sql
CREATE TABLE course_enrollments (
    student_id INTEGER,
    course_id INTEGER,
    semester VARCHAR(20),
    PRIMARY KEY (student_id, course_id, semester)
);
-- A student can take the same course, but only once per semester.

```

---

## 🔢 Automatic Numbering (SERIAL & IDENTITY)

PostgreSQL can automatically generate numbers for your Primary Keys so you don't have to.

| Type                                 | Description                                                              |
| ------------------------------------ | ------------------------------------------------------------------------ |
| **SERIAL**                           | Creates a sequence behind the scenes. Auto-increments 1, 2, 3...         |
| **BIGSERIAL**                        | Like SERIAL, but for massive tables (huge numbers).                      |
| **GENERATED ALWAYS AS IDENTITY**     | The modern standard. PostgreSQL prevents you from manually entering IDs. |
| **GENERATED BY DEFAULT AS IDENTITY** | Auto-generates IDs but allows manual entry if needed.                    |

**Identity Example:**

```sql
CREATE TABLE orders (
    order_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100)
);

```

---

## 🚀 Why are Primary Keys Important?

1. **No Duplicates**: Prevents identical records that ruin data accuracy.
2. **Relationships**: They are the "target" that Foreign Keys point to.
3. **Speed**: PostgreSQL creates a **B-tree Index** automatically, making searches lightning-fast.
4. **Replication**: Essential for syncing data between different servers.

---

## 🗑️ Managing Existing Tables

If you forgot to add a Primary Key when you created the table, use `ALTER TABLE`:

```sql
ALTER TABLE students ADD CONSTRAINT pk_students PRIMARY KEY (student_id);

```
````
